apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: twofold
  namespace: twofold
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "corner.firilov.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: twofold
          port: 80